### PR TITLE
Map AArch64 to EM_AARCH64 instead of EM_X86_64

### PR DESCRIPTION
**Pull request by morphis**

### CODE REVIEW

**Comment by RenaudWasTaken** [comment]
Hello there!

This was done as a workaround of the current libelf not supporting AARCH64 :)
I think the latest should support that platform so we should upgrade before fixing this workaround :)

**Comment by morphis** [comment]
@RenaudWasTaken Ah I see, however not fixing this would prevent things from running correctly on AArch64, right?

**Comment by RenaudWasTaken** [comment]
So I haven't dug too much into this but this specific instruction allows us to trick the build system to think that it's being built on an x86.

I suspect one of two things:
- libelf supports being compiled on AARCH and it just wasn't implemented / checked
- libelf has some platform specific requirements when reading some part of the elf file but we aren't inspecting the parts of the elf that would trigger a bug

**Comment by morphis** [comment]
@RenaudWasTaken Alright, from the tests I have done so far everything was building fine on AArch64 without changing to EM_AARCH64 but due to the lack of hardware I wasn't yet able to test with a real Nvidia GPU on AArch64. Fine to leave things as is. Are you planing to do a 1.0.7 release anytime soon? We're looking to include the latest changes in LXD to bring initial support for Nvidia on AArch64 but would much rather like to do that on top of an upstream release than cherry-picking or unreleased version.

**Comment by RenaudWasTaken** [comment]
I'm expecting to make a release within a month or two (at most).
I'm thinking of dropping the library package before that and only ship the binary before that :)

**Comment by RenaudWasTaken** [comment]
Let me know if you need a release sooner!

**Comment by morphis** [comment]
@RenaudWasTaken A month from now should be fine. Thanks!

**Pull request closed without merging**
