### PR TITLE
Add SLE15-SP1-x86-64 support

### PR DESCRIPTION
**Pull request by Hui-Zhi**
Add SLE15-SP1-x86-64 support.

### CODE REVIEW

**Comment by Hui-Zhi** [comment]
ping @RenaudWasTaken

**Comment by RenaudWasTaken** [comment]
Sorry completely forgot about that one!
Can you open it up on gitlab.com/nvidia?

**Comment by RenaudWasTaken** [comment]
Actually any difference between sles and opensuse? Could I just symlink the sles directory to the opensuse one?

**Comment by Hui-Zhi** [comment]
> Actually any difference between sles and opensuse? Could I just symlink the sles directory to the opensuse one?
Please don't, SLES is a commercial support OS version by SUSE but openSUSE is not, so some packages' version are different, and the most important part is the docker image generated by this request is based on registry.suse.com/suse/sle15, which is the commercial support version for SUSE's CaaSP (K8s based product). 

BTW, To generate the images and rpms, will need customer to register their SLES first. I think NVIDA has SLES register code since SUSE and NVIDIA have partner relationship. So please let me know if want to verify it but you don't have it.

**Comment by Hui-Zhi** [comment]
> Sorry completely forgot about that one!
> Can you open it up on gitlab.com/nvidia?

Sure, here: https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/17

**Comment by RenaudWasTaken** [comment]
Solved here: https://gitlab.com/nvidia/container-toolkit/libnvidia-container/-/merge_requests/17#note_327597446

**Pull request closed without merging**
